### PR TITLE
rewrite: Move to MiniFB C-API

### PR DESCRIPTION
**Pull request by DjDeveloperr**
no longer uses Rust, instead directly uses https://github.com/emoon/minifb

However, there's some downsides...
- Building is not trivial. At least on Windows.
- It's apparently missing some (or quite a lot) features compared to `rust_minifb` (by same author).

### CODE REVIEW

**Comment by DjDeveloperr** [comment]
While this new approach is way simpler, I feel like it's a way more limited API.
What should we do now? Should we keep using Rust MiniFB (reopen #6 and complete it)? Or just stick to this C-API?
cc @konsumer 

Btw for WebGPU, I have made [deno_desktop](https://github.com/DjDeveloperr/deno_desktop) (prototype-ish).

**Comment by konsumer** [comment]
I am not sure. If you have a demo with WebGPU, maybe that would be better?  Is this accelerated? I am not stuck on using minifb, more like "use a regular web API to make an accelerated native deno app".

**Comment by konsumer** [comment]
Oh, wait, I see, it's a fork of deno. Hmm. I am really not sure.

**Comment by DjDeveloperr** [comment]
`deno_desktop` project's purpose is quite different from `minifb`, it's to render things drawn using WebGPU on a window while minifb's to quickly prototype emulators and such. I just mentioned it because I *think* we do not need to target WebGPU from `deno-minifb`. But yeah, you could quite easily write a WebGPU-based "minifb" using pure JS as well for deno_desktop, similar to [pixels](https://github.com/parasyte/pixels).

What do you think about rust_minifb vs minifb?

**Comment by konsumer** [comment]
> What do you think about rust_minifb vs minifb?

I'm not sure I understand the diff. I originally intended to use the rust lib. I guess I sort of thought it was the same thing, but I don;t have a strong opinion. It seems like it might be easier to use the rust version, but since my actual goal is just "open a window and use a web API to draw in it, in deno" I vote for whatever seems easier.

**Comment by DjDeveloperr** [comment]
The main downside I'm talking about is MiniFB C is missing some things such as setting title after creating window, resizing it from code, etc. The C-API seems rather limited, while MiniFB Rust has some more features, such as menus.

Being *easier* depends I think. MiniFB C API might be easier to integrate as you'll not need to write any other language code, but just plug in existing MiniFB library and call methods on it. While MiniFB Rust bindings would need another layer of Rust wrapping the MiniFB Rust API in simple extern C calls, we can tune it to Deno FFI and do optimizations and such. I would honestly prefer C API but the missing features are kinda downside to me. That not being able to set title one is... not what I expected.

**Comment by DjDeveloperr** [comment]
I'll instead continue work on completing Rust-based FFI bindings, because of these reasons:

- C API is limited and missing some common features
- Building the dylib is not fun on Windows
- We can tune the Rust bindings according to Deno FFI easily

Closing this, will re-open the previous PR when I have time to continue on it.

**Comment by konsumer** [comment]
I will update the README to point to rust minifb.

**Pull request closed without merging**
