### PR TITLE
WIP: Update to support Deno 1.17, and add new stuff

### PR DESCRIPTION
**Pull request by DjDeveloperr**

### CODE REVIEW

**Comment by DjDeveloperr** [comment]
Hmm, process seems to exit with `0xc0000374` (heap corruption) on Windows for me after some time when window is opened ...
EDIT: only seems to happen when I add a menu to it.

**Comment by DjDeveloperr** [comment]
😕 heap corruption also happening when I update title of the window too often (such as every frame)...

**Comment by DjDeveloperr** [comment]
I think we should use the C-API of minifb directly, instead of making a C-layer excessively, let alone the pain of managing Rust lifetimes in global HashMaps...

**Review by konsumer — APPROVED** [review]
Looks good!

**Comment by DjDeveloperr** [comment]
Closing, because I will eventually make a move to C-API of minifb instead

**Comment by DjDeveloperr** [comment]
Still can't get menu's to work reliably. Heap corruption is really weird

**Pull request closed without merging**
